### PR TITLE
AArch64 support

### PR DESCRIPTION
**Pull request by emfomenk**
While https://github.com/oneapi-src/oneDNN/pull/698 is still under internal review, I would like to pipeline the next step.

We would like to add AArch64 in a list of officially (but experimentally) supported architectures. Once we would have more comprehensive testing with benchdnn, we could drop the _experimental_ tag. We will work towards that.
- Some background: currently benchdnn is not run with `ctest` as it takes a lot of time (roughly 3-4 hours). We plan to split the input files into two sets: lightweight for CI (with target to fit into 1 hour on not-very-powerful systems) and advanced, for our nightly, where we will test extensively our jitted implementations. The lightweight tests should still have a good coverage to claim overall good quality of the library (especially given that generic implementations do not have a lot of potential places for bugs).

@nSircombe, may I ask to review the changes.

Here there are two things:
1. I can now build oneDNN for ARM on x64 CPU using cross compilation [1]. However, this currently I have to add an extra knob `-DDNNL_ARCH_OPT_FLAGS=""` to cmake, because otherwise it would pass `-mcpu=native` and fail, as host is x64. So commit b90e3bd makes this compiler flag conditional, and turns it on only if one builds oneDNN on ARM.
    - Side comment. On x64 we decided to get rid of `-mcpu=native`, because that reduces the system oneDNN could be run on. Especially if it was built on newer processors (like Haswell), while people could still use IvyBridges or older systems. Does ARM have the same problem? Or AArch64 is more or less uniform for different processors? Say I build the library on Cortex-XXX, but try to run it on Cortex-YYY. Would `-mcpu=native` allow me to do that?
2. Documentation update, that says about **experimental** support of AArch64. Could you please review the wording? I was slightly confused whether I should call the support for ARM 64-bit Architecture, or 64-bit ARM Architecture v8, or simply ARMv8-A... So, I ended up with ARM 64-bit Architecture (AArch64).

---

[1]
``` bash
$ sudo apt-get install gcc-aarch64-linux-gnu g++-aarch64-linux-gnu
$ export CXX=aarch64-linux-gnu-g++
$ export CC=aarch64-linux-gnu-gcc
$ cmake .. \
    -DCMAKE_SYSTEM_NAME=Linux \
    -DCMAKE_SYSTEM_PROCESSOR=AARCH64 \
    -DCMAKE_LIBRARY_PATH=/usr/aarch64-linux-gnu/lib
$ make -j

$ file src/libdnnl.so.1.4
src/libdnnl.so.1.4: ELF 64-bit LSB shared object, ARM aarch64, version 1 (GNU/Linux), dynamically linked, BuildID[sha1]=c31d9a5c29629c46d606a20ebe62ce0e6283b265, with debug_info, not stripped
```

### CODE REVIEW

**Comment by emfomenk** [comment]
Not sure if mentioning a person in PR description notifies them...
So tagging @nSircombe explicitly :)

**Comment by nSircombe** [comment]
Hi @emfomenk, 
Thanks for the heads up - the first “at” in the PR did make it through to me. I’ll take a closer look at this and get back to you.

**Comment by nSircombe** [comment]
Hi @emfomenk 

A couple of thoughts...
1. While there's a lot in common with the x86 flags, in practice the landscape's a bit different on Arm, and we typically recommend building with `-mcpu=native`, for both GCC and Armclang. 
`-mcpu=native` sets both the appropriate micro-architectural tuning (`-mtune`) and the supported target architecture (`-march`). This will not be uniform across different SoCs, but without it, the compiler will default to `-mcpu=generic`, which will be portable across targets which implement Armv8-a. This won't offer the performance of micro-architectural tuning (remembering that there's some considerable scope for variation in the Arm ecosystem with both Arm and our partners designing CPUs), more importantly some architectural features are only available on certain revisions of Armv8, or as an option extension (at the discretion of the implementor). 
So forgoing the `-mcpu=native` will generate less performant code, but also prevent the generation of instructions for features like fp16 and bfloat16, and [SVE](https://developer.arm.com/docs/101726/latest/explore-the-scalable-vector-extension-sve/what-is-the-scalable-vector-extension) - admittedly not an issue for oneDNN at present!
It is of course possible to just set an appropriate `-mtune` to enable generation of such instructions, if you know that the target you're compiling for will support them. Or to set `-mcpu` to a specific target, e.g. `-mcpu=neoverse-n1`. 

2. Yes, I think the wording looks fine - with just one tiny change in branding! Arm should just be "Arm", no longer all caps (I realise that it still appears as ARM all over the place!)

**Comment by emfomenk** [comment]
Thanks for the review, @nSircombe!

1. Ok, I see. Well, as long as `-mcpu=native` is pretty standard behavior for Arm ecosystem I am more than fine with that. For those who needs something special there is always a `DNNL_ARCH_OPT_FLAGS` flag :)

2. Thanks! I applied the changes.

Just a heads up -- the PR with directory restructure is almost get into our internal master, and I hope it will be propagated to github later this week. We also will enable non-x64 testing (on x64 though) as soon as the PR gets into master.

**Comment by emfomenk** [comment]
And here we are. Everything is in master :)
Thanks for the help @nSircombe!

**Pull request closed without merging**
